name: Build Project

on:
  push:
  workflow_dispatch:

jobs:
  Build:
    strategy:
      matrix:
        generator: [ roaster, javapoet, gizmo, asm ]
    uses: evanchooly/workflows/.github/workflows/build.yml@master
    with:
      java: 17
      maven-flags: -Dgenerator=${{ matrix.generator }}