name: Pull Requests

on:
  pull_request:
    paths-ignore:
      - '.github/**'

jobs:
  Build:
    strategy:
      matrix:
        generator: [ roaster, javapoet, gizmo, asm ]
    uses: evanchooly/workflows/.github/workflows/pull-request.yml@master
    with:
      java: 17
      maven-flags: -Dgenerator=${{ matrix.generator }}